### ISSUE TITLE
Unable to get download data from files with symbolic links

### ISSUE THREAD

**Issue by apoorvrocks** [OpenNeuroDerivatives/ds000228-fmriprep#1]
Hello,
I am a Master's student at IISC who is interested in using this dataset for a project. I am not able to get the contents of the files.
Running- git annex get 'folder path' gives the following error-
failed
get sub-pixar154/func/sub-pixar154_task-pixar_desc-brain_mask.nii.gz (not available) 
  No other repository is known to contain the file.

Could you please direct me on how to download the dataset?
Apoorv Pandey

**Comment by jbwexler** [comment]
Thanks for bringing this to our attention. I think it should be fixed now - let me know if you still have trouble with it.
